export const PROVIDERS_LIST = 'PROVIDERS_LIST';
export const PROVIDERS_LIST_PENDING = 'PROVIDERS_LIST_PENDING';
export const PROVIDERS_LIST_FULFILLED = 'PROVIDERS_LIST_FULFILLED';
export const PROVIDERS_LIST_REJECTED = 'PROVIDERS_LIST_REJECTED';

export const PROVIDERS_STATES_LIST = 'PROVIDERS_STATES_LIST';
export const PROVIDERS_STATES_LIST_PENDING = 'PROVIDERS_STATES_LIST_PENDING';
export const PROVIDERS_STATES_LIST_FULFILLED = 'PROVIDERS_STATES_LIST_FULFILLED';
export const PROVIDERS_STATES_LIST_REJECTED = 'PROVIDERS_STATES_LIST_REJECTED';

export const PROVIDERS_CREATE = 'PROVIDERS_CREATE';
export const PROVIDERS_CREATE_PENDING = 'PROVIDERS_CREATE_PENDING';
export const PROVIDERS_CREATE_FULFILLED = 'PROVIDERS_CREATE_FULFILLED';
export const PROVIDERS_CREATE_REJECTED = 'PROVIDERS_CREATE_REJECTED';

export const PROVIDERS_UPDATE = 'PROVIDERS_UPDATE';
export const PROVIDERS_UPDATE_PENDING = 'PROVIDERS_UPDATE_PENDING';
export const PROVIDERS_UPDATE_FULFILLED = 'PROVIDERS_UPDATE_FULFILLED';
export const PROVIDERS_UPDATE_REJECTED = 'PROVIDERS_UPDATE_REJECTED';

export const PROVIDERS_DETAILS_GET = 'PROVIDERS_DETAILS_GET';
export const PROVIDERS_DETAILS_GET_PENDING = 'PROVIDERS_DETAILS_GET_PENDING';
export const PROVIDERS_DETAILS_GET_FULFILLED = 'PROVIDERS_DETAILS_GET_FULFILLED';
export const PROVIDERS_DETAILS_GET_REJECTED = 'PROVIDERS_DETAILS_GET_REJECTED';

export const PROVIDERS_CONTACTS_LIST = 'PROVIDERS_CONTACTS_LIST';
export const PROVIDERS_CONTACTS_LIST_PENDING = 'PROVIDERS_CONTACTS_LIST_PENDING';
export const PROVIDERS_CONTACTS_LIST_FULFILLED = 'PROVIDERS_CONTACTS_LIST_FULFILLED';
export const PROVIDERS_CONTACTS_LIST_REJECTED = 'PROVIDERS_CONTACTS_LIST_REJECTED';
export const PROVIDERS_RESET_CONTACTS_LIST = 'PROVIDERS_CONTACTS_LIST';

export const PROVIDERS_CONTACT_TYPES_LIST = 'PROVIDERS_CONTACT_TYPES_LIST';
export const PROVIDERS_CONTACT_TYPES_PENDING = 'PROVIDERS_CONTACT_TYPES_PENDING';
export const PROVIDERS_CONTACT_TYPES_FULFILLED = 'PROVIDERS_CONTACT_TYPES_FULFILLED';
export const PROVIDERS_CONTACT_TYPES_REJECTED = 'PROVIDERS_CONTACT_TYPES_REJECTED';

export const PROVIDERS_CONTACT_CREATE = 'PROVIDERS_CONTACT_CREATE';
export const PROVIDERS_CONTACT_CREATE_PENDING = 'PROVIDERS_CONTACT_CREATE_PENDING';
export const PROVIDERS_CONTACT_CREATE_FULFILLED = 'PROVIDERS_CONTACT_CREATE_FULFILLED';
export const PROVIDERS_CONTACT_CREATE_REJECTED = 'PROVIDERS_CONTACT_CREATE_REJECTED';

export const PROVIDERS_CONTACT_UPDATE = 'PROVIDERS_CONTACT_UPDATE';
export const PROVIDERS_CONTACT_UPDATE_PENDING = 'PROVIDERS_CONTACT_UPDATE_PENDING';
export const PROVIDERS_CONTACT_UPDATE_FULFILLED = 'PROVIDERS_CONTACT_UPDATE_FULFILLED';
export const PROVIDERS_CONTACT_UPDATE_REJECTED = 'PROVIDERS_CONTACT_UPDATE_REJECTED';

export const PROVIDERS_CONTACT_MAPPING_CREATE = 'PROVIDERS_CONTACT_MAPPING_CREATE';
export const PROVIDERS_CONTACT_MAPPING_CREATE_PENDING = 'PROVIDERS_CONTACT_MAPPING_CREATE_PENDING';
export const PROVIDERS_CONTACT_MAPPING_CREATE_FULFILLED = 'PROVIDERS_CONTACT_MAPPING_CREATE_FULFILLED';
export const PROVIDERS_CONTACT_MAPPING_CREATE_REJECTED = 'PROVIDERS_CONTACT_MAPPING_CREATE_REJECTED';

export const PROVIDERS_CONTACT_MAPPING_UPDATE = 'PROVIDERS_CONTACT_MAPPING_UPDATE';
export const PROVIDERS_CONTACT_MAPPING_UPDATE_PENDING = 'PROVIDERS_CONTACT_MAPPING_UPDATE_PENDING';
export const PROVIDERS_CONTACT_MAPPING_UPDATE_FULFILLED = 'PROVIDERS_CONTACT_MAPPING_UPDATE_FULFILLED';
export const PROVIDERS_CONTACT_MAPPING_UPDATE_REJECTED = 'PROVIDERS_CONTACT_MAPPING_UPDATE_REJECTED';

export const PROVIDERS_CONTACT_MAPPING_LIST = 'PROVIDERS_CONTACT_MAPPING_LIST';
export const PROVIDERS_CONTACT_MAPPING_LIST_PENDING = 'PROVIDERS_CONTACT_MAPPING_LIST_PENDING';
export const PROVIDERS_CONTACT_MAPPING_LIST_FULFILLED = 'PROVIDERS_CONTACT_MAPPING_LIST_FULFILLED';
export const PROVIDERS_CONTACT_MAPPING_LIST_REJECTED = 'PROVIDERS_CONTACT_MAPPING_LIST_REJECTED';

export const RESET_PROVIDERS = 'RESET_PROVIDERS';

export const list = () => ({
    type: PROVIDERS_LIST,
});

export const listStates = () => ({
    type: PROVIDERS_STATES_LIST,
});

export const get = (providerId) => ({
    type: PROVIDERS_DETAILS_GET,
    payload: { providerId },
});

export const create = (provider, callback) => ({
    type: PROVIDERS_CREATE,
    payload: { provider, callback },
});

export const update = (provider, callback) => ({
    type: PROVIDERS_UPDATE,
    payload: { provider, callback },
});

export const getContacts = (providerId) => ({
    type: PROVIDERS_CONTACTS_LIST,
    payload: { providerId },
});

export const resetContacts = () => ({
    type: PROVIDERS_RESET_CONTACTS_LIST,
});

export const listAssociattypes = () => ({
    type: PROVIDERS_CONTACT_TYPES_LIST,
});

export const createContact = (contact, callback) => ({
    type: PROVIDERS_CONTACT_CREATE,
    payload: { contact, callback },
});

export const updateContact = (contact, callback) => ({
    type: PROVIDERS_CONTACT_UPDATE,
    payload: { contact, callback },
});

export const getContactsMapping = (providerId) => ({
    type: PROVIDERS_CONTACT_MAPPING_LIST,
    payload: { providerId },
});

export const createProviderContactMapping = (contact, callback) => ({
    type: PROVIDERS_CONTACT_MAPPING_CREATE,
    payload: { contact, callback },
});

export const updateProviderContactMapping = (contact, callback) => ({
    type: PROVIDERS_CONTACT_MAPPING_UPDATE,
    payload: { contact, callback },
});
