export const SERVICES_LIST = 'SERVICES_LIST';
export const SERVICES_LIST_PENDING = 'SERVICES_LIST_PENDING';
export const SERVICES_LIST_FULFILLED = 'SERVICES_LIST_FULFILLED';
export const SERVICES_LIST_REJECTED = 'SERVICES_LIST_REJECTED';

export const SERVICES_CONNECTONS_LIST = 'SERVICES_CONNECTONS_LIST';
export const SERVICES_CONNECTONS_LIST_PENDING = 'SERVICES_CONNECTONS_LIST_PENDING';
export const SERVICES_CONNECTONS_LIST_FULFILLED = 'SERVICES_CONNECTONS_LIST_FULFILLED';
export const SERVICES_CONNECTONS_LIST_REJECTED = 'SERVICES_CONNECTONS_LIST_REJECTED';

export const SERVICES_TYPES_LIST = 'SERVICES_TYPES_LIST';
export const SERVICES_TYPES_LIST_PENDING = 'SERVICES_TYPES_LIST_PENDING';
export const SERVICES_TYPES_LIST_FULFILLED = 'SERVICES_TYPES_LIST_FULFILLED';
export const SERVICES_TYPES_LIST_REJECTED = 'SERVICES_TYPES_LIST_REJECTED';

export const SERVICES_CREATE = 'SERVICES_CREATE';
export const SERVICES_CREATE_PENDING = 'SERVICES_CREATE_PENDING';
export const SERVICES_CREATE_FULFILLED = 'SERVICES_CREATE_FULFILLED';
export const SERVICES_CREATE_REJECTED = 'SERVICES_CREATE_REJECTED';

export const SERVICES_CONNECTION_AUTH_TYPES = 'SERVICES_CONNECTION_AUTH_TYPES';
export const SERVICES_CONNECTION_AUTH_TYPES_PENDING = 'SERVICES_CONNECTION_AUTH_TYPES_PENDING';
export const SERVICES_CONNECTION_AUTH_TYPES_FULFILLED = 'SERVICES_CONNECTION_AUTH_TYPES_FULFILLED';
export const SERVICES_CONNECTION_AUTH_TYPES_REJECTED = 'SERVICES_CONNECTION_AUTH_TYPES_REJECTED';

export const SERVICES_CONNECTION_CREATES = 'SERVICES_CONNECTION_CREATES';
export const SERVICES_CONNECTION_CREATES_PENDING = 'SERVICES_CONNECTION_CREATES_PENDING';
export const SERVICES_CONNECTION_CREATES_FULFILLED = 'SERVICES_CONNECTION_CREATES_FULFILLED';
export const SERVICES_CONNECTION_CREATES_REJECTED = 'SERVICES_CONNECTION_CREATES_REJECTED';

export const SERVICES_CONNECTION_COPY = 'SERVICES_CONNECTION_COPY';
export const SERVICES_CONNECTION_COPY_PENDING = 'SERVICES_CONNECTION_COPY_PENDING';
export const SERVICES_CONNECTION_COPY_FULFILLED = 'SERVICES_CONNECTION_COPY_FULFILLED';
export const SERVICES_CONNECTION_COPY_REJECTED = 'SERVICES_CONNECTION_COPY_REJECTED';

export const SERVICES_OPTIONS_LIST = 'SERVICES_OPTIONS_LIST';
export const SERVICES_OPTIONS_LIST_PENDING = 'SERVICES_OPTIONS_LIST_PENDING';
export const SERVICES_OPTIONS_LIST_FULFILLED = 'SERVICES_OPTIONS_LIST_FULFILLED';
export const SERVICES_OPTIONS_LIST_REJECTED = 'SERVICES_OPTIONS_LIST_REJECTED';

export const SERVICES_OPTION_CREATE = 'SERVICES_OPTION_CREATE';
export const SERVICES_OPTION_CREATE_PENDING = 'SERVICES_OPTION_CREATE_PENDING';
export const SERVICES_OPTION_CREATE_FULFILLED = 'SERVICES_OPTION_CREATE_FULFILLED';
export const SERVICES_OPTION_CREATE_REJECTED = 'SERVICES_OPTION_CREATE_REJECTED';

export const SERVICES_OPTION_UPDATE = 'SERVICES_OPTION_UPDATE';
export const SERVICES_OPTION_UPDATE_PENDING = 'SERVICES_OPTION_UPDATE_PENDING';
export const SERVICES_OPTION_UPDATE_FULFILLED = 'SERVICES_OPTION_UPDATE_FULFILLED';
export const SERVICES_OPTION_UPDATE_REJECTED = 'SERVICES_OPTION_UPDATE_REJECTED';

export const SERVICES_CONNECTION_GET = 'SERVICES_CONNECTION_GET';
export const SERVICES_CONNECTION_GET_PENDING = 'SERVICES_CONNECTION_GET_PENDING';
export const SERVICES_CONNECTION_GET_FULFILLED = 'SERVICES_CONNECTION_GET_FULFILLED';
export const SERVICES_CONNECTION_GET_REJECTED = 'SERVICES_CONNECTION_GET_REJECTED';

export const SERVICES_CONNECTION_BODY_TYPES = 'SERVICES_CONNECTION_BODY_TYPES';
export const SERVICES_CONNECTION_BODY_TYPES_PENDING = 'SERVICES_CONNECTION_BODY_TYPES_PENDING';
export const SERVICES_CONNECTION_BODY_TYPES_FULFILLED = 'SERVICES_CONNECTION_BODY_TYPES_FULFILLED';
export const SERVICES_CONNECTION_BODY_TYPES_REJECTED = 'SERVICES_CONNECTION_BODY_TYPES_REJECTED';

export const SERVICES_CONNECTION_TEST = 'SERVICES_CONNECTION_TEST';
export const SERVICES_CONNECTION_TEST_PENDING = 'SERVICES_CONNECTION_TEST_PENDING';
export const SERVICES_CONNECTION_TEST_FULFILLED = 'SERVICES_CONNECTION_TEST_FULFILLED';
export const SERVICES_CONNECTION_TEST_REJECTED = 'SERVICES_CONNECTION_TEST_REJECTED';
export const SERVICES_CONNECTION_TEST_RESET = 'SERVICES_CONNECTION_TEST_REJECTED';

export const SERVICES_CONNECTION_RESULTS = 'SERVICES_CONNECTION_RESULTS';
export const SERVICES_CONNECTION_RESULTS_PENDING = 'SERVICES_CONNECTION_RESULTS_PENDING';
export const SERVICES_CONNECTION_RESULTS_FULFILLED = 'SERVICES_CONNECTION_RESULTS_FULFILLED';
export const SERVICES_CONNECTION_RESULTS_REJECTED = 'SERVICES_CONNECTION_RESULTS_REJECTED';

export const SERVICES_CONNECTION_RESULT_UPDATE = 'SERVICES_CONNECTION_RESULT_UPDATE';
export const SERVICES_CONNECTION_RESULT_UPDATE_PENDING = 'SERVICES_CONNECTION_RESULT_UPDATE_PENDING';
export const SERVICES_CONNECTION_RESULT_UPDATE_FULFILLED = 'SERVICES_CONNECTION_RESULT_UPDATE_FULFILLED';
export const SERVICES_CONNECTION_RESULT_UPDATE_REJECTED = 'SERVICES_CONNECTION_RESULT_UPDATE_REJECTED';
export const SERVICES_CONNECTION_RESULT_UPDATE_RESET = 'SERVICES_CONNECTION_RESULT_UPDATE_RESET';

export const SERVICES_CONNECTION_STATE_TYPES = 'SERVICES_CONNECTION_STATE_TYPES';
export const SERVICES_CONNECTION_STATE_TYPES_PENDING = 'SERVICES_CONNECTION_STATE_TYPES_PENDING';
export const SERVICES_CONNECTION_STATE_TYPES_FULFILLED = 'SERVICES_CONNECTION_STATE_TYPES_FULFILLED';
export const SERVICES_CONNECTION_STATE_TYPES_REJECTED = 'SERVICES_CONNECTION_STATE_TYPES_REJECTED';

export const SERVICES_CONNECTION_STATE_UPDATE = 'SERVICES_CONNECTION_STATE_UPDATE';
export const SERVICES_CONNECTION_STATE_UPDATE_PENDING = 'SERVICES_CONNECTION_STATE_UPDATE';
export const SERVICES_CONNECTION_STATE_UPDATE_FULFILLED = 'SERVICES_CONNECTION_STATE_UPDATE_FULFILLED';
export const SERVICES_CONNECTION_STATE_UPDATE_REJECTED = 'SERVICES_CONNECTION_STATE_UPDATE_REJECTED';

export const SERVICES_CONTACT_DETAIL_LIST = 'SERVICES_CONTACT_DETAIL_LIST';
export const SERVICES_CONTACT_DETAIL_LIST_PENDING = 'SERVICES_CONTACT_DETAIL_LIST_PENDING';
export const SERVICES_CONTACT_DETAIL_LIST_FULFILLED = 'SERVICES_CONTACT_DETAIL_LIST_FULFILLED';
export const SERVICES_CONTACT_DETAIL_LIST_REJECTED = 'SERVICES_CONTACT_DETAIL_LIST_REJECTED';

export const SERVICES_CONTACT_DETAIL_CREATE = 'SERVICES_CONTACT_DETAIL_CREATE';
export const SERVICES_CONTACT_DETAIL_CREATE_PENDING = 'SERVICES_CONTACT_DETAIL_CREATE_PENDING';
export const SERVICES_CONTACT_DETAIL_CREATE_FULFILLED = 'SERVICES_CONTACT_DETAIL_CREATE_FULFILLED';
export const SERVICES_CONTACT_DETAIL_CREATE_REJECTED = 'SERVICES_CONTACT_DETAIL_CREATE_REJECTED';

export const SERVICES_CONTACT_DETAIL_UPDATE = 'SERVICES_CONTACT_DETAIL_UPDATE';
export const SERVICES_CONTACT_DETAIL_UPDATE_PENDING = 'SERVICES_CONTACT_DETAIL_UPDATE_PENDING';
export const SERVICES_CONTACT_DETAIL_UPDATE_FULFILLED = 'SERVICES_CONTACT_DETAIL_UPDATE_FULFILLED';
export const SERVICES_CONTACT_DETAIL_UPDATE_REJECTED = 'SERVICES_CONTACT_DETAIL_UPDATE_REJECTED';

export const RESET_SERVICES = 'RESET_SERVICES';

export const list = (providerId) => ({
    type: SERVICES_LIST,
    payload: { providerId },
});

export const listConnections = (serviceId) => ({
    type: SERVICES_CONNECTONS_LIST,
    payload: { serviceId },
});

export const listServiceTypes = () => ({
    type: SERVICES_TYPES_LIST,
});

export const create = (service, callback) => ({
    type: SERVICES_CREATE,
    payload: { service, callback },
});

export const listAuthTypes = () => ({
    type: SERVICES_CONNECTION_AUTH_TYPES
});

export const createConnection = (serviceConnection, callback) => ({
    type: SERVICES_CONNECTION_CREATES,
    payload: { serviceConnection, callback },
});

export const copyConnection = (connectionId, callback) => ({
    type: SERVICES_CONNECTION_COPY,
    payload: { connectionId, callback },
});

export const listServiceOptions = (serviceId) => ({
    type: SERVICES_OPTIONS_LIST,
    payload: { serviceId },
});

export const createServiceOption = (serviceOption, callback) => ({
    type: SERVICES_OPTION_CREATE,
    payload: { serviceOption, callback },
});

export const updateServiceOption = (serviceOption, optionId, callback) => ({
    type: SERVICES_OPTION_UPDATE,
    payload: { serviceOption, optionId, callback },
});

export const getConnection = (connectionId) => ({
    type: SERVICES_CONNECTION_GET,
    payload: { connectionId },
});

export const testServiceConnection = (connection, callback) => ({
    type: SERVICES_CONNECTION_TEST,
    payload: { connection, callback },
});

export const resetTestServiceConnection = () => ({
    type: SERVICES_CONNECTION_TEST_RESET,
});

export const listResultsType = () => ({
    type: SERVICES_CONNECTION_RESULTS,
});

export const updateConnectionResult = (ConnectionResult, callback) => ({
    type: SERVICES_CONNECTION_RESULT_UPDATE,
    payload: { ConnectionResult, callback },
});

export const listBodyTypes = () => ({
    type: SERVICES_CONNECTION_BODY_TYPES,
});

export const listStateTypes = () => ({
    type: SERVICES_CONNECTION_STATE_TYPES,
});

export const updateConnectionState = (connectionState, callback) => ({
    type: SERVICES_CONNECTION_STATE_UPDATE,
    payload: { connectionState, callback },
});

export const listServiceContacts = (serviceId) => ({
    type: SERVICES_CONTACT_DETAIL_LIST,
    payload: { serviceId },
});

export const createServiceContact = (contact, callback) => ({
    type: SERVICES_CONTACT_DETAIL_CREATE,
    payload: { contact, callback },
});

export const updateServiceContact = (contact, callback) => ({
    type: SERVICES_CONTACT_DETAIL_UPDATE,
    payload: { contact, callback },
});
