export const SETTINGS_CONTACT_DATA_TYPES_LIST = 'SETTINGS_CONTACT_DATA_TYPES_LIST';
export const SETTINGS_CONTACT_DATA_TYPES_LIST_PENDING = 'SETTINGS_CONTACT_DATA_TYPES_LIST_PENDING';
export const SETTINGS_CONTACT_DATA_TYPES_LIST_FULFILLED = 'SETTINGS_CONTACT_DATA_TYPES_LIST_FULFILLED';
export const SETTINGS_CONTACT_DATA_TYPES_LIST_REJECTED = 'SETTINGS_CONTACT_DATA_TYPES_LIST_REJECTED';

export const SETTINGS_CONTACT_DATA_TYPES_CREATE = 'SETTINGS_CONTACT_DATA_TYPES_CREATE';
export const SETTINGS_CONTACT_DATA_TYPES_CREATE_PENDING = 'SETTINGS_CONTACT_DATA_TYPES_CREATE_PENDING';
export const SETTINGS_CONTACT_DATA_TYPES_CREATE_FULFILLED = 'SETTINGS_CONTACT_DATA_TYPES_CREATE_FULFILLED';
export const SETTINGS_CONTACT_DATA_TYPES_CREATE_REJECTED = 'SETTINGS_CONTACT_DATA_TYPES_CREATE_REJECTED';

export const SETTINGS_CONTACT_DATA_TYPES_UPDATE = 'SETTINGS_CONTACT_DATA_TYPES_UPDATE';
export const SETTINGS_CONTACT_DATA_TYPES_UPDATE_PENDING = 'SETTINGS_CONTACT_DATA_TYPES_UPDATE_PENDING';
export const SETTINGS_CONTACT_DATA_TYPES_UPDATE_FULFILLED = 'SETTINGS_CONTACT_DATA_TYPES_UPDATE_FULFILLED';
export const SETTINGS_CONTACT_DATA_TYPES_UPDATE_REJECTED = 'SETTINGS_CONTACT_DATA_TYPES_UPDATE_REJECTED';


export const RESET_SETTINGS = 'RESET_SETTINGS';

export const listContactDataTypes = () => ({
    type: SETTINGS_CONTACT_DATA_TYPES_LIST,
});

export const createContactDataType = (dataType, callback) => ({
    type: SETTINGS_CONTACT_DATA_TYPES_CREATE,
    payload: { dataType, callback },
});

export const updateContactDataType = (dataType, callback) => ({
    type: SETTINGS_CONTACT_DATA_TYPES_UPDATE,
    payload: { dataType, callback },
});